version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    env_file: .env
    cap_add:
      - NET_ADMIN
    ports:
      - 9696:9696 # Prowlarr GUI
      - 8989:8989 # Sonarr GUI
      - 8080:8080 # Qbittorrent GUI access
      - 6881:6881 # Qbittorrent Torrenting
      - 6881:6881/udp # Qbittorrent Torrenting
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=openvpn
      - SERVER_REGIONS=United Kingdom