---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    env_file: .env
    cap_add:
      - NET_ADMIN
    ports:
      - 9696:9696 # Prowlarr GUI
      - 8989:8989 # Sonarr GUI
      - 8080:8080 # Qbittorrent GUI access
      - 6881:6881 # Qbittorrent Torrenting
      - 6881:6881/udp # Qbittorrent Torrenting
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=openvpn
      - SERVER_REGIONS=United Kingdom
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: "service:gluetun"
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./prowlarr:/config
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./sonarr:/config
      - ~/library:/tv
      - ~/library:/downloads
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./qbittorrent:/config
      - ~/library:/downloads
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./jellyfin/conf:/config
      - ./jellyfin/cache:/cache
      - ~/library:/media
    restart: 'always'
    extra_hosts:
      - "host.docker.internal:host-gateway"